#!/usr/bin/expect

set timeout 20
set host "ssh.cluster128.hosting.ovh.net"
set user "studihp-applications"
set password "11FRjvlk25"

spawn ssh -o StrictHostKeyChecking=no $user@$host "mkdir -p ~/appli-facturation && cd ~/appli-facturation && echo '---NODE_VERSION---' && node -v && echo '---NPM_VERSION---' && npm -v && echo '---DIR_LIST---' && ls -la && echo '---END---'"

expect "password:"
send "$password\r"

expect -ex "---END---"
